### ISSUE TITLE
Notify doctor when status is re-updated on the same day

### ISSUE THREAD

**Issue by QuangTran304** [SamanthaGuillemette/SOEN390#10]
**Description**: 
As a patient, I want to notify the doctors when my status is re-updated on the same day so that they can have a look into my profile to see if I turned sick or recovered from Covid, or I simply made a mistake. 

**Acceptance criteria**:
Given: The user is logged in as a patient. 
When: The user modifies the previously completed status. 
Then: The application notifies the doctor(s) who are monitoring the patient about the change. 

**Sub-task:**

- [x] #143
- [x] #144

**Comment by SamanthaGuillemette** [comment]
merged to develop!
