### ISSUE TITLE
Notify Covid-19 patients & self-quarantine individuals to update status daily

### ISSUE THREAD

**Issue by QuangTran304** [SamanthaGuillemette/SOEN390#12]
**Description**: 
As a doctor or health official, I want to notify those who are in self-quarantine or those who are confirmed with COVID-19 every day, so that they can update their status through our platform.

**Acceptance criteria**:
Given: The user is logged in as a doctor or health official. 
When: There are patients who have COVID-19 as a status (in self quarantine or confirmed).
Then: The application sends them a daily notification to update their status. 

**Sub-task:**

- [x] #147
- [x] Back-end connection

**Comment by lailaalhalabi** [comment]
implemented pull request #325
