### ISSUE TITLE
Able to Sign in with Different Emails (Client)

### ISSUE THREAD

**Issue by MarwaKhalid** [SamanthaGuillemette/SOEN390#184]
On the client app, whether I use my client email or the admin email, I'm able to sign in.

**Comment by tusharraval102** [comment]
Hi @MarwaKhalid, I was wondering if you could give me the steps to reproduce the problem and I am unable to reproduce it on my end. Thanks!

**Comment by tusharraval102** [comment]
This issue has been solved.
