### ISSUE TITLE
Refactor: Remove old implementation of PatientList and PatientProfile

### ISSUE THREAD

**Issue by smarkandu** [SamanthaGuillemette/SOEN390#189]
Remove the non-DB implementations for PatientList and PatientProfile.

**Comment by QuangTran304** [comment]
Let's do this a bit later in this Sprint so that you don't need to do the refactor twice because I'm going to merge my work to the "Develop" branch (Related to PatientProfile from Client-app)
.

**Comment by smarkandu** [comment]
This was already done and merged into develop.  Not sure why this wasn't closed before.  Closing it now.
