### ISSUE TITLE
Arrange Appointments

### ISSUE THREAD

**Issue by QuangTran304** [SamanthaGuillemette/SOEN390#2]
**Description**: 
As a doctor, I want to be able to arrange appointments with a COVID-19 patient so that I can send notifications to the patient (email or SMS).

**Sub-tasks**:

- [x] #221
- [x] #222
- [x] Admin logic & backend
- [x] Client logic & backend

**Acceptance criteria**:
Given: The user is logged in as a doctor. 
When: The user clicks on a patient to organize an appointment. 
Then: The user is shown the patient with a way to make an appointment and notify the patient.

**Comment by SamanthaGuillemette** [comment]
merged to develop!
