### ISSUE TITLE
Plan backend structure

### ISSUE THREAD

**Issue by SamanthaGuillemette** [SamanthaGuillemette/SOEN390#233]
collections needed:
- [x] Notifications
- [x] Symptoms
- [x] Diary
- [x] Appointments

Consolidations:
- [x] Combine Patients and Clients
- [x] Combine Doctors and Admins (sub-collection?)

**Comment by tusharraval102** [comment]
Refactoring for the database:

Need to figure out how to refactor the database, and how to access patients and doctors. Right now, there is a mess of patients, clients, doctors, and admins. We need to consolidate the patients and clients, and the doctors and admin.

**Comment by SamanthaGuillemette** [comment]
Update on Issue:

- Some fields of dr info in client app are not present in the admin collection. This needs to be revised.
- Also Diary sub-collection isn't created yet.

**Comment by SamanthaGuillemette** [comment]
Done!
