### ISSUE TITLE
The admin system crashes when clients signup

### ISSUE THREAD

**Issue by liuwei-tianshu** [SamanthaGuillemette/SOEN390#270]
Steps to reproduce:
1 click the signup link on page: https://admin-covidtracker.web.app/
2 it crashes

A serious problem with high priority as the admin portal is not usable.

![signup the admin portal](https://user-images.githubusercontent.com/55549554/159577912-d18adbb9-0f97-4a3f-befb-052e889e70df.gif)

![20220322171735](https://user-images.githubusercontent.com/55549554/159577925-715c0899-8835-49ce-bc93-2fb81f95cd9f.jpg)

**Comment by liuwei-tianshu** [comment]
Please assign a QA to test all the workflow of the system.

**Comment by QuangTran304** [comment]
Thank you for reporting. I believe the bug should be fixed now. Can you please give it another try @liuwei-tianshu 
<img width="1552" alt="Screen Shot 2022-03-22 at 10 16 55 PM" src="https://user-images.githubusercontent.com/45047536/159611590-b4a647b3-5d0b-4cf1-b4e6-759e7db16010.png">
<img width="1552" alt="Screen Shot 2022-03-22 at 10 19 36 PM" src="https://user-images.githubusercontent.com/45047536/159611594-24a84af2-da58-4fe2-917f-2643e7d79ec7.png">
<img width="1552" alt="Screen Shot 2022-03-22 at 10 20 50 PM" src="https://user-images.githubusercontent.com/45047536/159611596-f6641122-ff4d-4818-ba00-84ae9da40efe.png">

**Comment by liuwei-tianshu** [comment]
It works now.
