### ISSUE TITLE
Bug 1- Email Validation in the Admin Application

### ISSUE THREAD

**Issue by AliZ786** [SamanthaGuillemette/SOEN390#280]
The following bug was produced when checking the workflow of the admin app.

![image](https://user-images.githubusercontent.com/59709752/159806948-a5998c7b-4211-4ea3-b2bc-b853b9c1883d.png)
![image](https://user-images.githubusercontent.com/59709752/159807000-b9a9c166-713b-4f7d-a4cf-b476c6d2bca6.png)

1. The following is not an email at all, would need to add an email validation in the code
2. This is not available in the Client application either.

**Comment by AliZ786** [comment]
![Bug1](https://user-images.githubusercontent.com/59709752/159811904-8d9ddcf2-c64e-4bdc-956a-b8cdbb836c0b.gif)

Video of the bug

**Comment by smarkandu** [comment]
Assigned to @tusharraval102, since he worked on this part.  Note this occurs with both the Admin and Client app.
