### ISSUE TITLE
Doctor sigup successfully even with an invalid birthday

### ISSUE THREAD

**Issue by liuwei-tianshu** [SamanthaGuillemette/SOEN390#282]
Reproduce steps on admin:
1 signup as a doctor with an invalid birthday, it "looks" like the doctor signs up successfully
2 I label it as a high priority because when that doctor signs in again, there will be an error message.
3 Also, sometimes when I input an invalid birthday, there is no prompt.

You can either remove the validation of birthday or implement it well.
Please assign one or two QA to test the application carefully. 

Sometimes, you can assign everyone to test it. The testing is **HUGE** work!

![sigup error](https://user-images.githubusercontent.com/55549554/159815935-1ad8158c-3dba-498e-bf14-18526d8708e0.gif)

**Comment by AliZ786** [comment]
Thank you for bringing this to our attention @liuwei-tianshu

**Comment by liuwei-tianshu** [comment]
The system is not friendly to use now. 

There are still minor defects:
1 My personal thinking is that it is not a good idea to implement the system as a "black" model regarding health. I thought the system provides several choices of color models for clients to select. However, the "black" model is the only one. 
We usually use blue, green, etc. colors to make people feel conformable regarding health. Just my own opinion.

2 a minor problem
Perhaps you can refer to the demo site of Solidus on GitHub: https://github.com/solidusio/solidus#demo
Actually, all of these systems are similar even they are in different domains.
![20220323203854](https://user-images.githubusercontent.com/55549554/159819179-2a0f105e-4151-49d5-8ffd-22e47aa4d6a1.jpg)

![20220323204303](https://user-images.githubusercontent.com/55549554/159819580-55cfd11d-f84c-464d-9a77-cb7b852d28ad.jpg)

3 I was wondering you can let someone who is not familiar with it try to use the system. I believe there will be more defects be found by real clients.

4 Also, please provide a simple description of how to use it on README. People may do not understand what is the patient portal or admin portal. They may also do not understand how to use the patient portal in a mobile phone browser or in chrome.

5 In a word, please test it more by QAs.

**Comment by smarkandu** [comment]
Hi sir, I saw your comment regarding the justification of this bug as "high priority":

_"I label it as a high priority because when that doctor signs in again, there will be an error message."_

Yet in the animated gif you posted, I didn't see an error.  Nor were we able to repro any error using the date you used.

Also, shouldn't "high priority" only be used for cases where a bug causes the system to crash, etc?  In this case, it just seems to be a case of bad data, which doesn't hinder the app in terms of stability, etc.

**Comment by smarkandu** [comment]
Hi sir, I saw your comment regarding the justification of this bug as "high priority":

_"I label it as a high priority because when that doctor signs in again, there will be an error message."_

Yet in the animated gif you posted, I didn't see an error.  Nor were we able to repro any error using the date you used.

Also, shouldn't "high priority" only be used for cases where a bug causes the system to crash, etc?  In this case, it just seems to be a case of bad data, which doesn't hinder the app in terms of stability, etc

**Comment by liuwei-tianshu** [comment]
> Hi sir, I saw your comment regarding the justification of this bug as "high priority":
> 
> _"I label it as a high priority because when that doctor signs in again, there will be an error message."_
> 
> Yet in the animated gif you posted, I didn't see an error. Nor were we able to repro any error using the date you used.
> 
> Also, shouldn't "high priority" only be used for cases where a bug causes the system to crash, etc? In this case, it just seems to be a case of bad data, which doesn't hinder the app in terms of stability, etc


@smarkandu 
Sorry, I made a mistake. This is the real one:
My intention is that the birthday after the current day is not valid.

![sigup error](https://user-images.githubusercontent.com/55549554/159844161-2ea994d3-b929-4b80-8b3f-5cc837bdbd78.gif)

**Comment by liuwei-tianshu** [comment]
The blue color made me confused.
I thought it indicates that the valued input is valid. Actually, it indicates that the value comes from input history.
That is why I made a mistake. Sorry.

![20220324005122](https://user-images.githubusercontent.com/55549554/159844779-2aee2391-0879-4329-9a43-ec25edec1018.jpg)

**Comment by liuwei-tianshu** [comment]
@smarkandu 
"I label it as a high priority because when that doctor signs in again, there will be an error message."

When I sign in using that account, I just input the user name instead of email. So this bug links to #280

**Comment by liuwei-tianshu** [comment]
You are right. The crash must be a bug with high priority. 

However, other situations may also be labeled as a high priority, especially when it blocks the usage of the workflow. 
The end-user does not have a strong background in computer science and patience/sufferance to try on the web pages if they face any problems. That is why your team should test the workflow carefully.

**Comment by smarkandu** [comment]
Right, but does this bug block the workflow for signing up?  I don't think it does (user can register successfully), hence I think it should most likely be normal priority for this bug.

Also as a side note: bear in mind that right now we're focusing on getting all of the functionalities done first.  Once this has been completed, we do plan on going over everything and locking down what can be inputted, who can do what, etc.

**Comment by liuwei-tianshu** [comment]
Actually, the demo should be tested comprehensively during each sprint. We do not demand the testing in the first sprints because it is not deployed online. My personal suggestion is to test it ASAP. I will share the link with other TAs when we have the meeting to adjust the grades.

![Optimized-Illustration-from-Adobe-Stock-for-ITC-Agile-Methodology-Post-1536x432](https://user-images.githubusercontent.com/55549554/159851567-e7617ec9-6fb2-4328-9bd6-d20e994ba354.jpg)
![agile_scrum_process_for_software_development_slide01](https://user-images.githubusercontent.com/55549554/159851568-6c621911-9fba-47a0-82f3-f8767bc1e5a4.jpg)

**Comment by MarwaKhalid** [comment]
Hi @liuwei-tianshu ,

You mentioned earlier in this issue that the name of the patient should be adjusted to indicate it's a linkable. Is this better?

![image](https://user-images.githubusercontent.com/71287263/159991516-f219368a-10a6-4037-8531-860c7792e753.png)

**Comment by liuwei-tianshu** [comment]
> 



> Hi @liuwei-tianshu ,
> 
> You mentioned earlier in this issue that the name of the patient should be adjusted to indicate it's a linkable. Is this better?
> 
> ![image](https://user-images.githubusercontent.com/71287263/159991516-f219368a-10a6-4037-8531-860c7792e753.png)

I think it looks much better now. You can make your decision about it by yourself. I just report this bug to show that the system still has many defects/bugs and it needs more testing. Usually, when we find bugs, there must be more bugs underneath.

**Comment by AliZ786** [comment]
This was not really a bug @liuwei-tianshu more of a suggestion you made. Which is why we asked you.

**Comment by liuwei-tianshu** [comment]
The developer may not fix some bugs with low priority or due to time constraints. 

However, the QA must test it carefully and report everything.
