### ISSUE TITLE
Bug 3 - CSS overall errors in the Client application

### ISSUE THREAD

**Issue by AliZ786** [SamanthaGuillemette/SOEN390#283]
The overall styling has some issues with the client application.

Some CSS overflows with the bottom navbar 

![image](https://user-images.githubusercontent.com/59709752/159846818-7e873dbb-6132-4b2f-bf71-11a776359c22.png)

![image](https://user-images.githubusercontent.com/59709752/159846901-6a0f0e0f-405d-4c0b-9138-76e4ec029783.png)

![image](https://user-images.githubusercontent.com/59709752/159846967-6e22ac1a-88de-4b5b-b928-be01645f6d7b.png)

**Comment by liuwei-tianshu** [comment]
Please also verify it on the mobile phone after fixing it. Sometimes it behaviors a little differently.

**Comment by liuwei-tianshu** [comment]
Maybe the font size is a bit small when using the mobile phone. I am not sure, you can check it.  An impression of the first glance is important even you implemented it very well.
