### ISSUE TITLE
Chat to new database architecture

### ISSUE THREAD

**Issue by tusharraval102** [SamanthaGuillemette/SOEN390#331]
The doctor patient list has been changed therefore the chat feature needs to be updated. Furthermore, the chat will be updated to take into account that a doctor has not been assigned to a patient yet. The same will be done for the doctor, when they have no patients. 

- [ ] Change database calls 
- [ ] Add helper text when no doctor/patient is assigned

**Comment by SamanthaGuillemette** [comment]
merged to develop!
