### ISSUE TITLE
Patient diary to update locations

### ISSUE THREAD

**Issue by QuangTran304** [SamanthaGuillemette/SOEN390#38]
**Descriptions**:
As a patient, I would like to update my diary (building, the places have been using postcode, GPS ... diary is optional) daily. So that doctors can view the patient's symptoms, and health officers can track patients' possible contact or self-quarantine.

**Acceptance criteria**:
Given: The user is logged in as a patient.
When: The user clicks on add diary.
Then: The user is able to modify their diary.

**Sub-task**:

- [x] #157
- [x] #158

**Comment by SamanthaGuillemette** [comment]
merged to develop!
