### ISSUE TITLE
Create a similar "List of symptoms" page for patients (on the patient app)

### ISSUE THREAD

**Issue by SamanthaGuillemette** [SamanthaGuillemette/SOEN390#80]
Description:
As a patient, I want to see my list of details so that I can review my status, temperature, weight, list of symptoms, etc.

Additional details:

Similar #9
Given: The user is logged in as a patient.
When: The patient clicks on their profile.
Then: The application shows a list of given details about the patient.

Sub-tasks:
- [x] Created UI Symptoms Table (Client)
- [x] symptoms entry modal
- [x] #140 
- [x] display symptoms

**Comment by QuangTran304** [comment]
@SamanthaGuillemette Sam, can you add some notes here to clarify the issue. Saleha and me is confusing about this & the Diary feature?
