### ISSUE TITLE
List of Patients with Details (Admin)

### ISSUE THREAD

**Issue by MarwaKhalid** [SamanthaGuillemette/SOEN390#89]
Description:
As an admin or doctor, I want to see the list of patients with details (assigned doctor, upcoming appointment, etc) so that I can monitor each patient. 

Acceptance Criteria:
Given: The user is logged in as an admin or doctor.
When: The patient clicks on patients.
Then: The application should be redirected to the Patients Page which shows a list of patients with details such as assigned doctors and more.

Subtasks:
- [X] #109 
- [x] #171

**Comment by SamanthaGuillemette** [comment]
to fix flagged highlight
